apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: concat-spec
spec:
  analyzers:
  - clusterVersion:
      outcomes:
      - fail:
          message: The Admin Console requires at least Kubernetes 1.16.0
          when: < 1.16.0
      - pass:
          message: Your cluster meets the recommended and required versions of Kubernetes
  - clusterVersion:
      outcomes:
      - fail:
          message: The Admin Console requires at least Kubernetes 1.16.0
          when: < 1.16.0
      - pass:
          message: Your cluster meets the recommended and required versions of Kubernetes
  - containerRuntime:
      outcomes:
      - fail:
          message: The Admin Console does not support using the gvisor runtime
          when: == gvisor
      - pass:
          message: A supported container runtime is present on all nodes
  - cephStatus: {}
  - longhorn: {}
  - clusterPodStatuses:
      outcomes:
      - fail:
          message: 'Status: {{ .Status.Reason }}'
          when: '!= Healthy'
  - statefulsetStatus: {}
  - deploymentStatus: {}
  - jobStatus: {}
  - replicasetStatus: {}
  - weaveReport:
      reportFileGlob: kots/kurl/weave/kube-system/*/weave-report-stdout.txt
  - textAnalyze:
      checkName: Weave Status
      exclude: ''
      fileName: kots/kurl/weave/kube-system/weave-net-*/weave-status-stdout.txt
      ignoreIfNoFiles: true
      outcomes:
      - fail:
          message: Weave is not ready
      - pass:
          message: Weave is ready
      regex: 'Status: ready'
  - textAnalyze:
      checkName: Weave Report
      exclude: ''
      fileName: kots/kurl/weave/kube-system/weave-net-*/weave-report-stdout.txt
      ignoreIfNoFiles: true
      outcomes:
      - fail:
          message: Weave is not ready
      - pass:
          message: Weave is ready
      regex: '"Ready": true'
  - textAnalyze:
      checkName: Inter-pod Networking
      exclude: ''
      fileName: kots/goldpinger/*/kotsadm-*/goldpinger-statistics-stdout.txt
      ignoreIfNoFiles: true
      outcomes:
      - fail:
          message: Some nodes have pod communication issues
          when: OK = false
      - pass:
          message: Goldpinger can communicate properly
      regexGroups: '"OK": ?(?P<OK>\w+)'
  - nodeResources:
      checkName: Node status check
      outcomes:
      - fail:
          message: Not all nodes are online.
          when: nodeCondition(Ready) == False
      - pass:
          message: All nodes are online.
  collectors:
  - clusterInfo: {}
  - clusterResources: {}
  - ceph: {}
  - longhorn: {}
  - exec:
      args:
      - -U
      - kotsadm
      collectorName: kotsadm-postgres-db
      command:
      - pg_dump
      containerName: kotsadm-postgres
      name: kots/admin_console
      selector:
      - app=kotsadm-postgres
      timeout: 10s
  - exec:
      args:
      - http://localhost:3030/goroutines
      collectorName: kotsadm-goroutines
      command:
      - curl
      containerName: kotsadm
      name: kots/admin_console
      selector:
      - app=kotsadm
      timeout: 10s
  - exec:
      args:
      - http://localhost:3030/goroutines
      collectorName: kotsadm-operator-goroutines
      command:
      - curl
      containerName: kotsadm-operator
      name: kots/admin_console
      selector:
      - app=kotsadm-operator
      timeout: 10s
  - logs:
      collectorName: kotsadm-postgres-db
      name: kots/admin_console
      selector:
      - app=kotsadm-postgres
  - logs:
      collectorName: kotsadm-api
      name: kots/admin_console
      selector:
      - app=kotsadm-api
  - logs:
      collectorName: kotsadm-operator
      name: kots/admin_console
      selector:
      - app=kotsadm-operator
  - logs:
      collectorName: kotsadm
      name: kots/admin_console
      selector:
      - app=kotsadm
  - logs:
      collectorName: kurl-proxy-kotsadm
      name: kots/admin_console
      selector:
      - app=kurl-proxy-kotsadm
  - logs:
      collectorName: kotsadm-dex
      name: kots/admin_console
      selector:
      - app=kotsadm-dex
  - logs:
      collectorName: kotsadm-fs-minio
      name: kots/admin_console
      selector:
      - app=kotsadm-fs-minio
  - logs:
      collectorName: kotsadm-s3-ops
      name: kots/admin_console
      selector:
      - app=kotsadm-s3-ops
  - logs:
      collectorName: registry
      name: kots/kurl
      namespace: kurl
      selector:
      - app=registry
  - logs:
      collectorName: ekc-operator
      name: kots/kurl
      namespace: kurl
      selector:
      - app=ekc-operator
  - secret:
      collectorName: kotsadm-replicated-registry
      includeValue: false
      key: .dockerconfigjson
      name: kotsadm-replicated-registry
  - logs:
      collectorName: rook-ceph-agent
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-agent
  - logs:
      collectorName: rook-ceph-mgr
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-mgr
  - logs:
      collectorName: rook-ceph-mon
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-mon
  - logs:
      collectorName: rook-ceph-operator
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-operator
  - logs:
      collectorName: rook-ceph-osd
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-osd
  - logs:
      collectorName: rook-ceph-osd-prepare
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-osd-prepare
  - logs:
      collectorName: rook-ceph-rgw
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-ceph-rgw
  - logs:
      collectorName: rook-discover
      name: kots/rook
      namespace: rook-ceph
      selector:
      - app=rook-discover
  - exec:
      args:
      - --local
      - status
      collectorName: weave-status
      command:
      - /home/weave/weave
      containerName: weave
      exclude: ''
      name: kots/kurl/weave
      namespace: kube-system
      selector:
      - name=weave-net
      timeout: 10s
  - exec:
      args:
      - --local
      - report
      collectorName: weave-report
      command:
      - /home/weave/weave
      containerName: weave
      exclude: ''
      name: kots/kurl/weave
      namespace: kube-system
      selector:
      - name=weave-net
      timeout: 10s
  - logs:
      collectorName: weave-net
      name: kots/kurl/weave
      namespace: kube-system
      selector:
      - name=weave-net
  - exec:
      args:
      - http://goldpinger.kurl.svc.cluster.local:80/check_all
      collectorName: goldpinger-statistics
      command:
      - curl
      containerName: kotsadm
      name: kots/goldpinger
      selector:
      - app=kotsadm
      timeout: 10s
  - copyFromHost:
      collectorName: kurl-host-preflights
      extractArchive: true
      hostPath: /var/lib/kurl/host-preflights
      image: alpine
      imagePullPolicy: IfNotPresent
      name: kots/kurl/host-preflights
      timeout: 1m
  - configMap:
      collectorName: kurl-current-config
      includeAllData: true
      name: kurl-current-config
      namespace: kurl
  - configMap:
      collectorName: kurl-last-config
      includeAllData: true
      name: kurl-last-config
      namespace: kurl
  - collectd:
      collectorName: collectd
      hostPath: /var/lib/collectd/rrd
      image: alpine
      imagePullPolicy: IfNotPresent
      timeout: 5m
